"""init2

Revision ID: 482881c55ff7
Revises: de2c6b5cd4cc
Create Date: 2023-01-26 12:25:05.351973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "482881c55ff7"
down_revision = "de2c6b5cd4cc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
