"""init

Revision ID: de2c6b5cd4cc
Revises: 
Create Date: 2023-01-26 12:12:48.803757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "de2c6b5cd4cc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roles_permiso")
    op.drop_table("usuario_roles")
    op.drop_table("permiso")
    op.drop_table("roles")
    op.drop_table("usuario")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "nombre_rol", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "descripcion", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="roles_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "usuario_roles",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("id_usuario", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("id_rol", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["id_rol"], ["roles.id"], name="usuario_roles_id_rol_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"], ["usuario.id"], name="usuario_roles_id_usuario_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="usuario_roles_pkey"),
    )
    op.create_table(
        "usuario",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "nombre_usuario",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "password", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="usuario_pkey"),
    )
    op.create_table(
        "roles_permiso",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("id_rol", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.Column("id_permiso", postgresql.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["id_permiso"], ["permiso.id"], name="roles_permiso_id_permiso_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["id_rol"], ["roles.id"], name="roles_permiso_id_rol_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="roles_permiso_pkey"),
    )
    op.create_table(
        "permiso",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "nombre_permiso",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "descripcion", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="permiso_pkey"),
    )
    # ### end Alembic commands ###
